name: automate-delivery-file-create

on:
  pull_request:
    branches: [master]
    types: [closed]
env:
  diff_path: "_dev/*"

jobs:
  run-actions:
    runs-on: ubuntu-latest
    if: github.head_ref == 'release' && github.event.pull_request.merged == true
    steps:
      - name: switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: fetch base branch
        run: git fetch origin ${{ github.base_ref }}
      - name: create delivery zip
        run: |
          diff_files=$(git diff --name-only origin/${{ github.base_ref }} HEAD -- "${diff_path}" --diff-filter=ACMR)
          git archive ${{ github.head_ref }} ${diff_files} -o delivery.zip
      - name: upload zip
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./delivery.zip
